### ISSUE TITLE
Questions about evaluation indicators

### ISSUE THREAD

**Issue by KevinYang95** [sudohainguyen/STAN-small-tumor-aware-network#1]
Thank you for sharing the code, I have some questions about the calculation of FPR in your paper. According to the formula of FPR, the result is between 0 and 1. But why your result appears to be greater than 1. Please tell me how you defined and calculated it. Thanks!

**Comment by sudohainguyen** [comment]
hey thanks for reaching out, sorry but I'm not the author of the paper, this is just my implementation that follows their declaration.

**Comment by bryarshareef** [comment]
Hello @ykeivn,
The FPR is calculated as the ratio between the number of false positives and actual positives, which is different than the commonly used formulation as the ratio between the number of false positives and actual negatives.  The false positive rate  is calculated as  FPR=  |χ_g  ∪ χ_(p )-〖 χ〗_g |/|χ_g | , where χ_g denotes the ground truth pixels of the tumor region, and χ_p is the predicted pixel sets. Based on this equation, if the size of the false positive regions is larger than the size of the actual positive regions, the FPR will be greater than 1.
