### ISSUE TITLE
Where to download the public dataset BUSIS?

### ISSUE THREAD

**Issue by imzhangyd** [sudohainguyen/STAN-small-tumor-aware-network#3]
I can't find the link of BUSIS, could you please show the dataset link? Thans a lot!

**Comment by sudohainguyen** [comment]
hi @imzhangyd , you might want to fill up some information in this [form](http://www2.docm.mmu.ac.uk/STAFF/m.yap/files/BUS_ReleaseAgreement.pdf).
Then send to dataset author's email (which you can find at the end of the document)

**Comment by imzhangyd** [comment]
Thank you！ @sudohainguyen But I mean another dataset used in STAN, which from paper “BUSIS: A Benchmark for Breast Ultrasound Image Segmentation”. Do you learn the download link about it？

**Comment by imzhangyd** [comment]
Thank you！ @sudohainguyen
